# Generated by Django 5.0.3 on 2024-04-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
